### PR TITLE
Feature and Testing simpsons rule

### PR DESCRIPTION
**Pull request by dnxjay**
# Title
 Add Visualization Script and Outputs for Simpson's Rule Integrals

## Linting
  - The visualize_integrals.py script was checked for linting using pylint

## Contents
  - This pull request introduces a new folder to organize and execute the visualization of Simpson's Rule integrals for the assigned functions. It includes:

A script to generate function plots, shade integral areas, and annotate results.
Pre-generated .png files for the assigned functions.

## Reviewer
  - @Cosmos491

### CODE REVIEW

**Review by jkblc — CHANGES_REQUESTED** [review]
First thing to fix would be the pylint errors including the incorrect import:
integrals/visualize_integrals.py:1:0: F0001: No module named integrals/visualize_integrals.py (fatal)
************* Module test_calculus
test_calculus.py:182:0: C0305: Trailing newlines (trailing-newlines)

**Comment by dnxjay** [comment]
> First thing to fix would be the pylint errors including the incorrect import: integrals/visualize_integrals.py:1:0: F0001: No module named integrals/visualize_integrals.py (fatal) ************* Module test_calculus test_calculus.py:182:0: C0305: Trailing newlines (trailing-newlines)

this should be a quick fix once my first PR gets merged into the main branch

**Comment by zbpetersbuf** [comment]
o I see the issue now

**Comment by zbpetersbuf** [comment]
@dnxjay should be ready to go now

**Comment by dnxjay** [comment]
> @dnxjay should be ready to go now

ready for review

**Comment by dnxjay** [comment]
@Cosmos491 can you review this please

**Comment by Cosmos491** [comment]
Ok, I will review this now

**Comment by Cosmos491** [comment]
Since, all checks have passed and I see no issue . I am going to approve the request

**Review by Cosmos491 — APPROVED** [review]

**Comment by zbpetersbuf** [comment]
@jkblc please remember to approve the request, its how you get the point for the review

**Comment by dnxjay** [comment]
@zbpetersbuf this should be ready to merge

**Comment by dnxjay** [comment]
@zbpetersbuf good for merging. conflicts were resolved

**Comment by zbpetersbuf** [comment]
@dnxjay Sorry I merged another persons request, once you update your branch i will merge it regardless if @jkblc finalizes their review.

**Comment by dnxjay** [comment]
> @dnxjay Sorry I merged another persons request, once you update your branch i will merge it regardless if @jkblc finalizes their review.

It's updated now

**Review by zbpetersbuf — APPROVED** [review]

**Pull request merged**
