### PR TITLE
Create calculus.py

### PR DESCRIPTION
**Pull request by abruns123**
This pull request adds the calculus.py file as well as the wrapper algorithm for the adaptive trapezoid.

Linting: Haven't fully tested the linting yet

Reviewers: Anyone may review.

### CODE REVIEW

**Comment by zbpetersbuf** [comment]
Thank you for making the calculus.py file, I was going to hold off until 8pm to give anyone who doesn't want to share files a chance to speak up but looks like there is going to be shared calculus.py and test_calculus.py, ill make the test_calculus.py and will try and avoid conflicts with your already made calculus.py

**Comment by zbpetersbuf** [comment]
be sure to possibly make and set a milestone for this pull request

**Review by jkblc — CHANGES_REQUESTED** [review]
Please fix the pylint complaints

**Comment by zbpetersbuf** [comment]
listing issues where fixed so I merged

**Pull request merged**
