### PR TITLE
Completed the wrapper implementation with scipy for root-finding

### PR DESCRIPTION
**Pull request by HeshamElsaman**
# The wrapper implementation for root-finding

## Linting
- It got 10.0/10.0

## Content
- Added the function to calculate the root of a given function
- Files Changed: calculus.py, test_calculus.py

## Reviewer
- @haiderabbas007

### CODE REVIEW

**Comment by HeshamElsaman** [comment]
@haiderabbas007 
This one is supposed to be good to go. Could you, please, review it as soon as possible? Appreciated.

**Comment by zbpetersbuf** [comment]
Ill check in the morning if this is reviewed then ill merge it

**Comment by haiderabbas007** [comment]
Yes I am reviewing it now

**Comment by zbpetersbuf** [comment]
are you having trouble approving the review?

**Review by haiderabbas007 — APPROVED** [review]
# PR Review

This PR is a good foundation for a Newton-Raphson wrapper and its test suite. Both are well-structured, functional, modular, and reusable. Here are a few suggestions:

### 1. Enhance the Wrapper Function (`root_tangent`):
- **Error Handling:** Add error handling to manage non-convergence or invalid inputs, such as division by zero.
- **Input Validation:** Ensure `function` and `fprime` are callable and `x0` is numeric.

### 2. Expand the Test Suite:
- **Diversity in Test Cases:** Add tests for functions with multiple roots, cases where the derivative is zero at the initial guess, and functions where Newton's method struggles to converge.
- **Edge Cases:** Test invalid inputs (e.g., `x0=None`, `function` not callable) to ensure the function raises appropriate exceptions.
- **Parameterization:** Use `pytest.mark.parametrize` to simplify repetitive test cases for different functions and initial guesses.

### 3. Improve Code Readability and Maintainability:
- **Docstring Enhancements:** Include usage examples in the `root_tangent` docstring to clarify how to use the function and clarify assumptions (e.g., differentiability of the function).
- **Test Naming:** Make test names more descriptive, e.g., `test_root_tangent_simple_case` or `test_root_tangent_zero_derivative`.

Everything else is fine.

**Review by zbpetersbuf — APPROVED** [review]
you will still need to resolve merge conflicts @HeshamElsaman

**Comment by HeshamElsaman** [comment]
@zbpetersbuf
Conflicts are resolved now. Thanks!

**Pull request merged**
