### PR TITLE
Integration Calculation using Adaptive Trapezoidal Method, Numpy Trapezoidal Method and the Scipy Trapezoidal Method

### PR DESCRIPTION
**Pull request by Cosmos491**
I have added the evaluate_integrals() calculates the integral of each function using:
1. Adaptive Trapezoidal Method (adaptive_trap_py)
2. Numpy Trapezoidal Method (trapezoid_numpy)
3. Scipy Trapezoidal Method (trapezoid_scipy)

I have implemented the Execution Time for each method which is measured using time.time(), and acts as a measure of efficiency. Accuracy is compared against the Scipy result, given a very brute assumption that it is the most accurate.

For accuracy comparison, Scipy's result is used as the benchmark. The accuracy is measured in terms of the number of correct significant digits. This approach provides a reasonable approximation for comparing the quality of different methods.

Expected output: Print the integral value, execution time, error, and number of correct digits for each integration method for each function.

Reviewer: @dnxjay

### CODE REVIEW

**Comment by Cosmos491** [comment]
@dnxjay I am getting: "calculus.py:636:0: R0914: Too many local variables (19/15) (too-many-locals)" as a warning. I do not understand this warning.

**Comment by zbpetersbuf** [comment]
@Cosmos491 it just means that in the function you are defining you got too many like constants or equations, so in
def funk(a,b):
      b=1
      j=2
      return a+b+d+j

b and j are local variables, in most cases you can shorten the amount by doing something like this

def funk(a,b):
      return a+b+1+2

**Comment by zbpetersbuf** [comment]
@Cosmos491, check in with pull 32 again, you never approved the pull request you just left a review message, you need to approve it to get points

**Comment by zbpetersbuf** [comment]
@Cosmos491 ill give you 10 min to approve the merge unless you say you need more time

**Comment by Cosmos491** [comment]
@zbpetersbuf I was not sure that I had to approve it too. I did approve it. Thanks for pointing that out

**Comment by Cosmos491** [comment]
@zbpetersbuf for some reason, I see this message of branch conflicts. How do I resolve it?

**Comment by zbpetersbuf** [comment]
@Cosmos491 click resolve conflicts and only delete the lines located at the number before each one
634 <<<<<<< main
638 =======
780 >>>>>>> main

**Comment by zbpetersbuf** [comment]
thats worded poorly but i think its clear

**Comment by zbpetersbuf** [comment]
and be sure to sync your main branch

**Comment by Cosmos491** [comment]
Thanks @zbpetersbuf for the help

**Comment by Cosmos491** [comment]
@zbpetersbuf So when I deleted the lines, all my code was removed and if I sync ( open pull request), I can see the file again?

**Comment by zbpetersbuf** [comment]
@Cosmos491 im sorry I dont think I understand, did you delete your code between the lines <<<<<<< main, and =======? that would be your code, and the code between ======= and >>>>>>> main would be someone else's code. if you deleted your code you can check back to earlier versions of your code, and if youre concerned you deleted someone else's code (you could do the same) or check ubsuny's branch

**Comment by zbpetersbuf** [comment]
@Cosmos491 you did delete someone else's code you can see it if you press the blue view rules to the right of 'merging is blocked' (the code you deleted will be highlighted red and to the left), also I do not think the 'import time' statement is allowed, but im not sure, you'll have to ask @laserlab that

**Comment by Cosmos491** [comment]
> @Cosmos491 you did delete someone else's code you can see it if you press the blue view rules to the right of 'merging is blocked' (the code you deleted will be highlighted red and to the left), also I do not think the 'import time' statement is allowed, but im not sure, you'll have to ask @laserlab that

Yeah, I believe I deleted @dnxjay part of the code by mistake. I am sorry man.

@laserlab Since I am supposed to compare the accuracy and efficiency of each imlplementation, I can use the time import ?
image

**Comment by dnxjay** [comment]
> @dnxjay Based upon your suggestions of adding assertions, test edge cases and the usage of mocks; I have updated the unit test file.
> 
> Both calculus.py and test_calculus.py is open for review

the linting issues still needs to be fixed

**Comment by Cosmos491** [comment]
> > @dnxjay Based upon your suggestions of adding assertions, test edge cases and the usage of mocks; I have updated the unit test file.
> > Both calculus.py and test_calculus.py is open for review
> 
> the linting issues still needs to be fixed

@dnxjay I fixed the listing issue now. I believe this PR is ready to be merged now

**Review by dnxjay — APPROVED** [review]
Execution proceeds as expected.
Passes all units tests and pylints with a score of 10/10.
Approving this for merge.

**Comment by laserlab** [comment]
> 'import time' statement is allowed, but im not sure, you'll have to ask @laserlab that

time is a python standard library and so no problem. Only things that you have to add to requirements we have to decide since it can break things

**Comment by zbpetersbuf** [comment]
@Cosmos491 you need to un delete that person's code i will not merge it otherwise

**Comment by Cosmos491** [comment]
Ok, but how do I do that? @zbpetersbuf

**Comment by zbpetersbuf** [comment]
I mean i think the proper way is to look back at previous commits, but you could also just copy and past (you might need to make sure that the past is correctly pasted) their code, you can do this by checking unsunny main calculus.py, or to see this more clearly scroll to the top of this pull request and click files changed where it will show you what you would change if i merged your branch

**Comment by Cosmos491** [comment]
> @Cosmos491 you need to un delete that person's code i will not merge it otherwise

I checked the UBsuny main calculus.py and I can see that code; it starts with def calculate integral() and its a complete code, so where is the issue?

**Comment by zbpetersbuf** [comment]
Screenshot 2024-11-25 at 1 00 26 PM

this is some of the code you deleted, i would suggest knocking on @laserlab door right now before class

**Comment by p-pxmpo** [comment]
I volunteer to review this PR if thats okay with you @Cosmos491

**Comment by Cosmos491** [comment]
@p-pxmpo Sure, go ahead. Now all the checks have been passed, and the code that was previously deleted was added to just before the start of def evaluate_integrals() in calculus.py.

Can you review this at your earliest convenience? as I need to make another PR for the plots. Thank you!

**Comment by p-pxmpo** [comment]
> @p-pxmpo Sure, go ahead. Now all the checks have been passed, and the code that was previously deleted was added to just before the start of def evaluate_integrals() in calculus.py.
> 
> Can you review this at your earliest convenience? as I need to make another PR for the plots. Thank you!

reviewing now thank you

**Review by p-pxmpo — APPROVED** [review]
evaluate_integrals function
- well structured.
- runs smoothly.
- docstrings are descriptive.

test_evaluate integrals
- pytest passed
- Exception handling is well implemented in the test cases.
- Docstrings in the tests explain their purpose, inputs, and assertions clearly.
- Good use of mocks, ensures that the test focuses on the integration method calls and their outputs.

Thank you @Cosmos491 I approve

**Comment by Cosmos491** [comment]
> evaluate_integrals function
> 
> * well structured.
> * runs smoothly.
> * docstrings are descriptive.
> 
> test_evaluate integrals
> 
> * pytest passed
> * Exception handling is well implemented in the test cases.
> * Docstrings in the tests explain their purpose, inputs, and assertions clearly.
> * Good use of mocks, ensures that the test focuses on the integration method calls and their outputs.
> 
> Thank you @Cosmos491 I approve

Thank you for the review @p-pxmpo 
So, I can go ahead and merge now or @zbpetersbuf will do it?

**Comment by p-pxmpo** [comment]
@zbpetersbuf please merge so I can fix the merge conflicts

**Comment by zbpetersbuf** [comment]
ok your good to go

**Review by zbpetersbuf — APPROVED** [review]

**Pull request merged**
