### PR TITLE
Find roots calculations

### PR DESCRIPTION
**Pull request by p-pxmpo**
For this assignment all pull requests going  forward should contain the following (please delete the placeholder text and add your own description)

# Title
  - Implementation of Root-Finding Methods with visualization via plots.

## Linting
  - The code has been linted. with acceptable errors.

## Contents
  - This pull request introduces a module that implements the root-finding functions onto the assigned functions listed in the task descriptions. 
  - The module includes both SciPy and pure Python implementations of the secant and bisection methods. 
  - It also provides utilities for calculating the accuracy of root approximations and plotting the results with function plots and saving as .png files.
 
## Labels and Milestones
  - ALL pull requests must have an attached label and Milestone before a reviewer can be assigned.

## Reviewer
  - No team mate therefore @dnxjay or @Cosmos491 can review due to somewhat similar task.

Any further questions on formatting pull requests can be asked in the issues tab or on discord. 
This document can be changed at any time.

### CODE REVIEW

**Comment by zbpetersbuf** [comment]
@p-pxmpo Im pretty sure all the code you made in the findroots.py file belongs in calculus.py, you will have to correct me if im wrong but i will not merge either of these pull requests until you correct me or fix this issue

Screenshot 2024-11-25 at 1 08 07 PM

**Review by dnxjay — CHANGES_REQUESTED** [review]
This is a well-organized and thoughtfully implemented module. 
Suggestions: 
-The docstring in apply_methods could clarify the expected format of the result
-Ensure that the test suite for this module includes tests for:
Boundary cases (e.g., intervals where no roots exist).
Functions with singularities.
Validation of accuracy calculations.
Whats needed for approval:
-Fix the pylint issue. Seems like its a simple fix, just lower the amount words in the line. Once thats done, the scope of this PR is introducing the module and basic functionality without extensive test coverage or optimization, it can be approved.
-update the branch

**Comment by zbpetersbuf** [comment]
> @p-pxmpo Im pretty sure all the code you made in the findroots.py file belongs in calculus.py, you will have to correct me if im wrong but i will not merge either of these pull requests until you correct me or fix this issue
> 
> Screenshot 2024-11-25 at 1 08 07 PM

I talked to @laserlab he said it was fine ignore this

**Comment by p-pxmpo** [comment]
Thank you @dnxjay and @Cosmos491 for the review! I will fix the line issue immediately

**Comment by dnxjay** [comment]
@p-pxmpo once you move the file into the calculus.py and fix the linting i can check the functionality and do the review again

**Comment by p-pxmpo** [comment]
> @p-pxmpo once you move the file into the calculus.py and fix the linting i can check the functionality and do the review again

Ok I will move code into claculus.py and delete this file

**Comment by dnxjay** [comment]
> > @p-pxmpo once you move the file into the calculus.py and fix the linting i can check the functionality and do the review again
> 
> Ok I will move code into claculus.py and delete this file

Theres one linting error

**Comment by dnxjay** [comment]
@p-pxmpo just remove the docstring you have from line 791-803 in the calculus.py file. Once you remove that the linting error will be gone

**Review by dnxjay — APPROVED** [review]
This code looks good. Functional and should get 10/10 once @p-pxmpo removes from docstrings thats not needed. Once those changes goes through, this should ready to be merged. 
One suggestion would be to move all your plots into its own folder for better organization

**Comment by p-pxmpo** [comment]
@Cosmos491 ready for your review!

**Comment by Cosmos491** [comment]
> @Cosmos491 ready for your review!

I will review it now, thanks!

**Comment by Cosmos491** [comment]
The code is well written and passes all the checks. However, I do have the following suggestions:
1. For small differences near zero, log10 might fail due to floating-point precision. Add an epsilon to handle this.
2. Currently, apply_methods returns only the roots. Adding metadata like method success/failure or accuracy would provide better insights.

Again, these suggestions are towards enhancing he functionality, for now I approve the PR.

**Review by Cosmos491 — APPROVED** [review]

**Comment by p-pxmpo** [comment]
> The code is well written and passes all the checks. However, I do have the following suggestions:
> 
> 1. For small differences near zero, log10 might fail due to floating-point precision. Add an epsilon to handle this.
> 2. Currently, apply_methods returns only the roots. Adding metadata like method success/failure or accuracy would provide better insights.
> 
> Again, these suggestions are towards enhancing he functionality, for now I approve the PR.

Thanks for the review! I will consider these functionality changes.

**Comment by p-pxmpo** [comment]
fixing merge conflict now

**Comment by zbpetersbuf** [comment]
@Cosmos491 why did you close this?

**Comment by p-pxmpo** [comment]
> @Cosmos491 why did you close this?

Accidentally closed, fixing now

**Comment by zbpetersbuf** [comment]
@p-pxmpo so its good to go correct?

**Comment by p-pxmpo** [comment]
@zbpetersbuf I accidentally closed trying to fix the merge conflict, my fault, Everything is fixed now.

**Comment by p-pxmpo** [comment]
> @p-pxmpo so its good to go correct?

Yep good to go

**Comment by zbpetersbuf** [comment]
alright no worries i was just confused

**Review by zbpetersbuf — APPROVED** [review]

**Pull request merged**
