### PR TITLE
Added plots for visualization for three function using Adaptive Trapezoidal, Numpy Trapezoidal and Scipy Trapezoidal

### PR DESCRIPTION
**Pull request by Cosmos491**
Added plots for visualization for three function using
1. Adaptive Trapezoidal
2. Numpy Trapezoidal
3. Scipy Trapezoidal

The three files are as follows:
1. Integral of exp(-1/x) is plotted and saved as exp(-1:x).png file that shows the integration result using the Adaptive Trapezoidal, Numpy Trapezoidal and Scipy Trapezoidal methods.
2. Integral of cos(1/x) is plotted and saved as cos(1:x).png file that shows the integration result using the Adaptive Trapezoidal, Numpy Trapezoidal and Scipy Trapezoidal methods.
3. Integral of x^3+1 is plotted and saved as (x^3)+1.png file that shows the integration result using the Adaptive Trapezoidal, Numpy Trapezoidal and Scipy Trapezoidal methods.

reviewer @dnxjay @zbpetersbuf

### CODE REVIEW

**Comment by p-pxmpo** [comment]
@Cosmos491 may I volunteer to review this PR? I need 1 more review

**Review by p-pxmpo — APPROVED** [review]
Great plots! very good visualization of the integrals of the functions. One small suggestion, you added the message shown in the screenshot below for the integral of x^3+1, for consistency purposes either add that message to the other plots as well or remove it. I will approve, thanks!

evalintegral

**Comment by Cosmos491** [comment]
> Great plots! very good visualization of the integrals of the functions. One small suggestion, you added the message shown in the screenshot below for the integral of x^3+1, for consistency purposes either add that message to the other plots as well or remove it. I will approve, thanks!
> 
> evalintegral

Thank you for the suggestion, I will remove it so that it is consistent with the other ones.

**Review by zbpetersbuf — APPROVED** [review]
please update, ill check again to merge, this will be the next pull i merge so no need to reupdate latter

**Comment by Cosmos491** [comment]
> please update, ill check again to merge, this will be the next pull i merge so no need to reupdate latter

already updated it @zbpetersbuf

**Pull request merged**
