### PR TITLE
unit test for find roots calculations

### PR DESCRIPTION
**Pull request by p-pxmpo**
For this assignment all pull requests going  forward should contain the following (please delete the placeholder text and add your own description)

# Title
  - Add unit tests for findroots.py.

## Linting
  - Yes, the code lints with acceptable errors. Most of the other errors are due to find roots calculations have not yet been merged into calculus.py.
  - Pytest run fails because find roots calculations is not found because they have not yet been merged into calculus.py  ( #40 ). Once that PR is merged it should pass.

## Contents
  - This pull request includes the addition of unit tests for several functions in the findroots.py module, including func_1_safe, func_2, func_3, calculate_accuracy, apply_methods, plot_function_with_roots, and find_roots.
  - Each function has corresponding tests to ensure correct behavior, including checks for edge cases, error handling, and visual output generation.

## Labels and Milestones
  - ALL pull requests must have an attached label and Milestone before a reviewer can be assigned.

## Reviewer
  - No team mate therefore @dnxjay or @Cosmos491 can review due to similar task.

Any further questions on formatting pull requests can be asked in the issues tab or on discord. 
This document can be changed at any time.

### CODE REVIEW

**Comment by zbpetersbuf** [comment]
@p-pxmpo I believe your root-finding test code should be in the test_calculus.py, not its own file you named test_findroots.py, if im mistaken then you will have to tell me

Screenshot 2024-11-25 at 1 08 07 PM

**Comment by abruns123** [comment]
I volunteer to review this one if no one else is already doing that.

**Comment by dnxjay** [comment]
i also can review

**Comment by zbpetersbuf** [comment]
> @p-pxmpo I believe your root-finding test code should be in the test_calculus.py, not its own file you named test_findroots.py, if im mistaken then you will have to tell me
> 
> Screenshot 2024-11-25 at 1 08 07 PM

I talked with @laserlab ignore this

**Comment by p-pxmpo** [comment]
> @p-pxmpo I believe your root-finding test code should be in the test_calculus.py, not its own file you named test_findroots.py, if im mistaken then you will have to tell me
> 
> Screenshot 2024-11-25 at 1 08 07 PM

I will move this code into test_calculus.py

**Comment by p-pxmpo** [comment]
@abruns123 @dnxjay ready for second review

**Comment by dnxjay** [comment]
The tests arent functional which im assuming is due to your first PR not being merged yet. Try to get that one up and running first then this one should be easier to receive functionality

**Comment by p-pxmpo** [comment]
> The tests arent functional which im assuming is due to your first PR not being merged yet. Try to get that one up and running first then this one should be easier to receive functionality

sounds good, I'll re-evaluate this PR once PR #40 gets merged.

**Comment by abruns123** [comment]
the only pylint errors involve a missing new line at the end and a few lines being too long.

**Comment by p-pxmpo** [comment]
> the only pylint errors involve a missing new line at the end and a few lines being too long.

fixed, im just waiting nnow for PR #40 to be merged so this code can be functional

**Comment by zbpetersbuf** [comment]
@p-pxmpo but you closed pull request 40, I gues i don't need to know but im just wondering if there was an issue

**Comment by p-pxmpo** [comment]
Fixing merghe conflict now

**Comment by p-pxmpo** [comment]
Merge conflict fixed, linting errors fixed, ready for review @abruns123 @zbpetersbuf

**Comment by p-pxmpo** [comment]
@dnxjay Could you also review? thanks!

**Comment by zbpetersbuf** [comment]
@p-pxmpo please check the pylint error, it seems to be a smaller problem but you will have to take it up with @laserlab before i do anything

**Comment by p-pxmpo** [comment]
> @p-pxmpo please check the pylint error, it seems to be a smaller problem but you will have to take it up with @laserlab before i do anything, or you could fix it

@zbpetersbuf Fixed the too general exceptions linting errors, pytest still runs good.

**Comment by p-pxmpo** [comment]
@zbpetersbuf @abruns123 @dnxjay awaiting your approval please, thanks!

**Comment by zbpetersbuf** [comment]
@p-pxmpo my approval is the second one, you only need one approval, mine is just to stop people from merging their own pull requests

**Review by abruns123 — APPROVED** [review]
pylint and pytest checks pass. Code looks good. Should be fine to merge

**Comment by p-pxmpo** [comment]
> pylint and pytest checks pass. Code looks good. Should be fine to merge

Thank you for the approval! @zbpetersbuf ready for your second approval.

**Review by zbpetersbuf — APPROVED** [review]

**Pull request merged**
