### PR TITLE
Added tests for Python implementation of Tangent

### PR DESCRIPTION
**Pull request by haiderabbas007**
# Add unit tests for the `tangent_pure_python` function in `test_calculus.py`

## Linting
  - Yes

## Contents
  - This PR introduces unit tests for the `tangent_pure_python` function defined in `calculus.py`. The new tests validate key aspects of the function's behavior, ensuring correctness and robustness under various scenarios.
  - Added six test cases in `test_calculus.py`:
  1. `test_convergence_tangent`: Validates positive root convergence for a simple quadratic function $(x^2 - 4)$.
  2. `test_negative_root_tangent`: Ensures convergence to the negative root $(x = -2)$.
  3. `test_non_convergence_tangent`: Verifies non-convergence behavior when the initial guess is far from any root and `maxiter` is reached.
  4. `test_zero_div_tangent`: Tests behavior when the derivative is zero, ensuring proper error handling.
  5. `test_tolerance_control_tangent`: Checks functionality under a stricter tolerance $10^-10$.
  6. `test_zero_root_tangent`: Validates convergence near a root of zero for the cubic function ($x^3).

## Suggested Reviewer(s)
  - @HeshamElsaman @zbpetersbuf

### CODE REVIEW

**Comment by haiderabbas007** [comment]
@HeshamElsaman I have made the changes as requested. For the (x) input in `fprime(x)` function inside `test_zero_div_tangent` function, I have removed it, although I have a few comments about it. It might result in function signature mismatch. The `tangent_pure_python` function calls `fprime(x0)` like this: 

```fprime_val = fprime(x0)```. 

If `fprime()` is defined without parameters, calling `fprime(x0)` might raise a `TypeError` because `fprime()` does not accept any arguments.

**Comment by HeshamElsaman** [comment]
@haiderabbas007 I guess I see what you mean now. Then I can suggest two things, either you return a zero in a nicer way like `x0 - x0`, `0 * x0`, or even `0 * (x0 - x0)` with adding the needed tolerance, or just add a linting exception to this.

**Comment by haiderabbas007** [comment]
> @haiderabbas007 I guess I see what you mean now. Then I can suggest two things, either you return a zero in a nicer way like `x0 - x0`, `0 * x0`, or even `0 * (x0 - x0)` with adding the needed tolerance, or just add a linting exception to this.

Ok, I have made the changes

**Comment by haiderabbas007** [comment]
@HeshamElsaman I have implemented the suggested changes and all the tests pass 100%. Thank you for your valuable input.

@zbpetersbuf

**Review by zbpetersbuf — APPROVED** [review]

**Pull request merged**
